packages: []
overrides:
  is-core-module: npm:@no-shims/is-core-module

catalog:
  '@eslint/js': ^9.21.0
  eslint: ^9.21.0
  eslint-flat-config-utils: ^2.0.1
  globals: ^16.0.0
  local-pkg: ^1.1.1

catalogs:
  dev:
    '@adufr/prettier-config': ^0.0.4
    '@eslint/config-inspector': ^1.0.2
    '@types/node': ^22.13.9
    ansis: ^3.17.0
    bumpp: ^10.0.3
    eslint-typegen: ^2.0.0
    prettier: ^3.5.3
    tsdown: ^0.6.4
    tsx: ^4.19.3
    typescript: ^5.8.2

  parsers:
    jsonc-eslint-parser: ^2.4.0
    vue-eslint-parser: ^10.1.1
    yaml-eslint-parser: ^1.3.0

  plugins:
    '@eslint-community/eslint-plugin-eslint-comments': ^4.4.1
    '@eslint/markdown': ^6.3.0
    '@unocss/eslint-plugin': ^66.1.0-beta.3
    eslint-config-flat-gitignore: ^2.1.0
    eslint-config-prettier: ^10.1.1
    eslint-plugin-antfu: ^3.1.1
    eslint-plugin-command: ^3.1.0
    eslint-plugin-de-morgan: ^1.2.0
    eslint-plugin-import-x: ^4.6.1
    eslint-plugin-jsdoc: ^50.6.3
    eslint-plugin-jsonc: ^2.19.1
    eslint-plugin-n: ^17.16.2
    eslint-plugin-perfectionist: ^4.10.1
    eslint-plugin-pnpm: ^0.1.2
    eslint-plugin-prettier: ^5.2.3
    eslint-plugin-regexp: ^2.7.0
    eslint-plugin-sxzz: ^0.2.1
    eslint-plugin-unicorn: ^57.0.0
    eslint-plugin-unused-imports: ^4.1.4
    eslint-plugin-vue: ^10.0.0
    eslint-plugin-yml: ^1.17.0
    typescript-eslint: ^8.26.0
